version: '3.8'

services:
    kiwiwi:
        build: .
        image: durumi/kiwiwi
        container_name: kiwiwi
        restart: always
        volumes:
            - .:/usr/src/app/
        environment:
            NODE_ENV: production
        entrypoint: ['/bin/bash', '-c']
        command:
            - |
                chmod +x docker-entrypoint.sh
                ./docker-entrypoint.sh
        depends_on:
            - db
    db:
        image: mariadb:11.4.2
        container_name: ${DATABASE_HOST}
        restart: always
        expose:
            - 3306
        volumes:
            - './db/conf.d:/etc/mysql/conf.d'
            - './db/data:/var/lib/mysql'
        environment:
            - ALLOW_EMPTY_PASSWORD=no
            - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MARIADB_USER=${DATABASE_USER}
            - MARIADB_DATABASE=${DATABASE_NAME}
            - MARIADB_PASSWORD=${DATABASE_PASSWORD}
networks:
    default:
        name: kiwiwi-network
