import { writeFileSync } from 'fs';
import puppeteer from 'puppeteer';

function parseCookieExpirationValue(expires) {
    let newValue = expires;

    if (expires === -1) {
        newValue = Date.now() + 365 * 86400 * 1000;
    }

    return Math.round(newValue);
}

function parseCookieValue(value) {
    return value.trim();
}

function parseCookieDomain(domain) {
    if (domain.startsWith('.')) {
        return domain;
    }
    return `.${domain}`;
}

function buildCookiesData(cookies) {
    return cookies
        .sort((cookieA, cookieB) => {
            return cookieA.domain > cookieB.domain ? 1 : -1;
        })
        .reduce((data, cookie) => {
            const newRow = [
                parseCookieDomain(cookie.domain),
                'TRUE',
                cookie.path,
                cookie.secure ? 'TRUE' : 'FALSE',
                parseCookieExpirationValue(cookie.expires),
                cookie.name,
                parseCookieValue(cookie.value),
            ];

            return `${data}\n${newRow.join('\t')}`;
        }, '# Netscape HTTP Cookie File\n# This was generated by Puppeteer\n\n');
}
const getCookies = async () => {
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    const page = await browser.newPage();

    await page.goto('https://www.youtube.com');
    const cookies = await browser.cookies();

    const netscapeCookies = buildCookiesData(cookies);

    writeFileSync('cookies.txt', netscapeCookies);

    await browser.close();
};

export default getCookies;
